// Package random contains logic related to randomly generating things.
package random

import "math/rand/v2"

// Dice represents one or more dice that can be rolled to generate a random number.
type Dice struct {
	// Count is the number of dice to roll.
	Count int
	// Sides is the number of sides on each die.
	Sides int
}

// Roll returns a random number generated by rolling the dice.
func (d *Dice) Roll() int {
	result := 0
	for range d.Count {
		result += rand.IntN(d.Sides) + 1
	}
	return result
}

// RollAll returns a random number generated by rolling all of the specified dice.
func RollAll(dice []*Dice) int {
	result := 0
	for _, d := range dice {
		result += d.Roll()
	}
	return result
}
